@startuml

title __UTILS's Class Diagram__\n

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace Utils {
          class com.museomaster.museomaster.TypyUzytkownikow.Utils.ListaWyszukanychZabytkowController {
              + exhibits_list : ListView<Exhibit>
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace Utils {
          class com.museomaster.museomaster.TypyUzytkownikow.Utils.PracownikUprawnionyDashboardController {
              + taks_list_textView : ListView
              + task_assigned_listView : ListView
              + task_ended_listview : ListView
              + initData()
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace Utils {
          class com.museomaster.museomaster.TypyUzytkownikow.Utils.PracownikUprawnionyPrzydzielZadanie {
              + give_task : Button
              + input_name_lbl : TextField
              + role_combobox : ComboBox
              + search_button : Button
              + ser_found_list : ListView
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace Utils {
          class com.museomaster.museomaster.TypyUzytkownikow.Utils.PracownikUtworzZadanieDashboardController {
              + Error_lbl : Text
              + desc_textfield : TextArea
              + ego_to_ex_btn : Button
              + end_date_datePicker : DatePicker
              + give_task_btn : Button
              + przydziel_zadanie_btn : VBox
              + stard_date_datePicker : DatePicker
              + subject_lbl : TextField
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace Utils {
          class com.museomaster.museomaster.TypyUzytkownikow.Utils.ProblemController {
              + report_btn : Button
              + report_text : TextArea
              + rr_lbl : Label
              + initialize()
              - onReportCreate()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace Utils {
          class com.museomaster.museomaster.TypyUzytkownikow.Utils.WyborZabytkowController {
              + add_button : Button
              + lista_wybranych_zab : ListView
              + sala_choice : ChoiceBox
              + typ_zadania : ChoiceBox
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace Utils {
          class com.museomaster.museomaster.TypyUzytkownikow.Utils.WyszukiwanieZabytkowController {
              + author_lbl : TextField
              + current_place_combobox : ChoiceBox<String>
              + error_lbl : Text
              + ex_name_lbl : TextField
              + firs_year_input : TextField
              + search_btn : Button
              + second_year_input : TextField
              + subject_combobox : ComboBox
              + tematyka_tf : TextField
              + time_made_combobox : ComboBox
              + initialize()
          }
        }
      }
    }
  }
  

  com.museomaster.museomaster.TypyUzytkownikow.Utils.ListaWyszukanychZabytkowController .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.Utils.PracownikUprawnionyDashboardController .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.Utils.PracownikUprawnionyPrzydzielZadanie .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.Utils.PracownikUtworzZadanieDashboardController .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.Utils.ProblemController .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.Utils.WyborZabytkowController .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.Utils.WyszukiwanieZabytkowController .up.|> javafx.fxml.Initializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
