@startuml

title __ZWYKLYKONSWERWATOR's Class Diagram__\n

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace ZwyklyKonswerwator {
          class com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ListaPrzydzielonychZaabytkowController {
              + lista_przydziel_zab : ListView
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace ZwyklyKonswerwator {
          class com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ZwyklyKonserwator {
              + PracownikTechnicznyPanel : BorderPane
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace ZwyklyKonswerwator {
          class com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ZwyklyKonserwatorDashboardController {
              + active_task_list : ListView
              + date_lb : Label
              + tasks_done : ListView
              + initialize()
          }
        }
      }
    }
  }
  

  namespace  {
    namespace om.museomaster.museomaster {
      namespace TypyUzytkownikow {
        namespace ZwyklyKonswerwator {
          class com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ZwyklyKonserwatorMenu {
              + lista_eksponatow : Label
              + lista_zadan_lbl : Label
              + logout_lbl : Label
              + report_btn : Button
              + initialize()
              - onLogout()
              - onMenuClick()
          }
        }
      }
    }
  }
  

  com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ListaPrzydzielonychZaabytkowController .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ZwyklyKonserwator .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ZwyklyKonserwatorDashboardController .up.|> javafx.fxml.Initializable
  com.museomaster.museomaster.TypyUzytkownikow.ZwyklyKonswerwator.ZwyklyKonserwatorMenu .up.|> javafx.fxml.Initializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
